@startuml
actor User as u
participant "Junit" as junit
participant "Testcontainers" as tc
participant "Redis Container" as rc
database "Redis Database" as rdb

u -> junit: Initiate Test
activate junit

group Quick Start
    junit -> tc: Before All
    activate tc
    tc -> rc: Start docker container
    activate rc
    rc -> rdb: Launch Redis DB
    activate rdb
    rdb --> rc: Redis Ready
    rc --> tc: Container Ready
    deactivate tc
    junit -> junit: Execute Dummy Test 1
    junit -> junit: Execute Dummy Test 2
    junit -> tc: After All
    activate tc
    tc -> rc: Stop docker container
    rc -> rdb: Stop Redis DB
    deactivate rdb
    rc --> tc: Container Stopped
    deactivate tc
    deactivate rc
end group

group Container Lifecycle Management Test
    group Dummy Test 1
        junit -> tc: Before Each
        activate tc
        tc -> rc: Start docker container
        activate rc
        rc -> rdb: Launch Redis DB
        activate rdb
        rdb --> rc: Redis Ready
        rc --> tc: Container Ready
        deactivate tc
        junit -> junit: test execution
        junit -> tc: After Each
        activate tc
        tc -> rc: Stop docker container
        rc -> rdb: Stop Redis DB
        deactivate rdb
        rc --> tc: Container Stopped
        deactivate tc
        deactivate rc
    end group

    group Dummy Test 2
        junit -> tc: Before Each
        activate tc
        tc -> rc: Start docker container
        activate rc
        rc -> rdb: Launch Redis DB
        activate rdb
        rdb --> rc: Redis Ready
        rc --> tc: Container Ready
        deactivate tc
        junit -> junit: test execution
        junit -> tc: After Each
        activate tc
        tc -> rc: Stop docker container
        rc -> rdb: Stop Redis DB
        deactivate rdb
        rc --> tc: Container Stopped
        deactivate tc
        deactivate rc
    end group
end group

junit --> u: Test Complete
@enduml
