@startuml
actor User as u
participant "Junit" as junit
participant "RedisService" as rs
participant "Testcontainers" as tc
participant "Redis Container" as rc
database "Redis Database" as rdb

u -> junit: Initiate Test
activate junit

group Redis Connection Tests
    junit -> tc: Initialize Container
    activate tc
    tc -> rc: Start Docker container
    activate rc
    rc -> rdb: Launch Redis DB
    activate rdb
    rdb --> rc: Redis Ready
    rc --> tc: Container Ready
    deactivate tc


    group test_RedisReachable
        junit -> rs: getConnection()
        activate rs
        rs --> rdb: getConnection
        rdb --> rs: Successful Connection
        rs --> junit: Successful Test
        deactivate rs
    end group

    group test_WrongConnectionInfo
        junit -> rs: getConnection()
        activate rs
        rs -> rdb: Try getConnection with Wrong Info
        rdb --> rs: Failed Connection
        rs --> junit: Successful Test
        deactivate rs
    end group

    group test_HostUnreachable
        junit -> tc: start test and stop container
        activate tc
        tc -> rc: Stop Docker container
        rc -> rdb: Stop Redis DB
        deactivate rdb
        rc --> tc: Container Stopped
        deactivate rc
        tc --> junit: Container Stopped
        deactivate tc
        junit -> rs: getConnection()
        activate rs
        rs -> rdb: Try getConnection with Stopped Redis
        rdb --> rs: Failed
        rs --> junit: Successful Test
        deactivate rs
    end group

    junit -> tc: Cleanup
    activate tc
    deactivate rdb
    deactivate rc
    tc --> junit: Container Stopped
    deactivate tc
end group

group Redis Interaction Tests
    junit -> tc: Initialize Container
    activate tc
    tc -> rc: Start Docker container
    activate rc
    rc -> rdb: Launch Redis DB
    activate rdb
    rdb --> rc: Redis Ready
    rc --> tc: Container Ready
    deactivate tc

    group test_Success
        junit -> rs: getSync()
        activate rs
        rs -> rdb: put & get
        rdb --> rs: Success
        rs --> junit: Successful Test
        deactivate rs
    end group

    junit -> tc: Cleanup
    activate tc
    tc -> rc: Stop Docker container
    rc -> rdb: Stop Redis DB
    deactivate rdb
    rc --> tc: Container Stopped
    deactivate rc
    tc --> junit: Container Stopped
    deactivate tc
end group

junit --> u: Test Complete
@enduml
