name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: 21

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.5-dind
        options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Build and test with Maven
        run: mvn clean verify  # Modify this command to match your Maven goals and options
