name: Java CI with Maven

on:
  push:
    branches:
      - '**'  # This will trigger the workflow on pushes to all branches

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.5-dind
        options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and test with Maven
        run: mvn clean verify  # Modify this command to match your Maven goals and options
